<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>demo</groupId>
		<artifactId>simple</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>simple-cal-feature</artifactId>
	<packaging>pom</packaging>

	<dependencies>
		<!-- <dependency>
			<groupId>demo</groupId>
			<artifactId>simple-cal-api</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>bundle</type>
		</dependency>
		<dependency>
			<groupId>demo</groupId>
			<artifactId>simple-cal-app</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>bundle</type>
		</dependency>
		<dependency>
			<groupId>demo</groupId>
			<artifactId>simple-cal-rest</artifactId>
			<version>0.0.1-SNAPSHOT</version>
			<type>bundle</type>
		</dependency> -->
	</dependencies>
	<build>
		<resources>
			<resource>
				<directory>src/main/feature</directory>
				<filtering>true</filtering>
				<targetPath>${project.build.directory}/feature</targetPath>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>resources</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<version>3.5.0</version>
				<executions>
					<execution>
						<id>attach-artifacts</id>
						<phase>package</phase>
						<goals>
							<goal>attach-artifact</goal>
						</goals>
						<configuration>
							<artifacts>
								<artifact>
									<file>target/feature/feature.xml</file>
									<type>xml</type>
									<classifier>features</classifier>
								</artifact>
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>